#!/bin/bash
#SBATCH --job-name=ospm
#SBATCH -p normal
#SBATCH -A AST23031
#SBATCH --output=logs/%x_%j.out
#SBATCH --error=logs/%x_%j.err
#SBATCH --time=01:30:00
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=32G
#SBATCH -n 1
#SBATCH -c 8

set -euo pipefail
module purge
module load python/3.12.11
module load gcc/12.2.0
export JULIA_BINDIR=/scratch/09909/n8lujan99/julia-1.10.10/bin
export PATH="$JULIA_BINDIR:$PATH"
export JULIA_DEPOT_PATH=/scratch/09909/n8lujan99/.julia
export JULIA_PKG_SERVER=""
unset LD_LIBRARY_PATH
unset LD_PRELOAD
export JULIA_NUM_THREADS="${SLURM_CPUS_PER_TASK}"

if [[ -z "${OSPM_REPO_ROOT:-}" ]]; then
    echo "[FATAL] OSPM_REPO_ROOT not set"
    exit 1
fi

REPO_ROOT="$OSPM_REPO_ROOT"
WHICH_GAL_FILE="$REPO_ROOT/which_galaxy"

if [[ ! -f "$WHICH_GAL_FILE" ]]; then
    echo "[FATAL] which_galaxy not found at $WHICH_GAL_FILE"
    exit 1
fi

GALAXY="$(tr -d '[:space:]' < "$WHICH_GAL_FILE")"

if [[ -z "$GALAXY" ]]; then
    echo "[FATAL] which_galaxy is empty"
    exit 1
fi

echo "[INFO] Galaxy: $GALAXY"
echo "[INFO] Repo root: $REPO_ROOT"
echo "[INFO] CPUs: ${SLURM_CPUS_PER_TASK}"
cd "$REPO_ROOT"

# DO NOT CALL setup IN SLURM
source .venv/bin/activate
export PYJULIA_USE_PYTHONCALL=1
export OSPM_USE_JULIA=1
export PYTHONPATH="$REPO_ROOT"
bash utils/start
